# fly.toml file generated for okid on 2023-03-25T20:34:36-07:00

app = "okid"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
